// Storage adapter contract for evidence documents (Sprint 4 / A1). Bytes live
// behind this interface so the rest of the app never touches a filesystem or a
// cloud SDK directly: dev/tests use the local-filesystem adapter; a hosted pilot
// swaps in Vercel Blob or an S3-compatible adapter via env, with no call-site
// change. Keys are opaque, generated by us (never a client filename), and every
// adapter MUST reject a key that escapes its namespace (path traversal).
export interface StorageAdapter {
  readonly backend: "local" | "blob" | "s3";
  /** Store bytes at `key`. Overwrites only when writing the SAME content to the
   *  same key (keys are content-addressed by the caller); callers never reuse a
   *  key for different bytes — a new document version gets a new key. */
  put(key: string, bytes: Uint8Array, contentType: string): Promise<void>;
  /** Read the bytes at `key`. Throws if absent. */
  getBytes(key: string): Promise<Uint8Array>;
  exists(key: string): Promise<boolean>;
  /** Remove the object at `key`. Idempotent: absent key is not an error. Used by
   *  the storage self-test to clean up its throwaway probe; document keys are
   *  never deleted in normal operation (a new version gets a new key). */
  delete(key: string): Promise<void>;
}

// A generated, traversal-safe key: <prefix>/<32-hex>.<ext>. The hex is random,
// so a key is unguessable and never derived from user input.
export function isSafeStorageKey(key: string): boolean {
  if (key.length === 0 || key.length > 512) return false;
  if (key.startsWith("/") || key.includes("\\")) return false;
  // No traversal, no empty/dot segments, no absolute paths.
  return key.split("/").every((seg) => seg.length > 0 && seg !== "." && seg !== "..");
}
